WebShop/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;
using WebShop.ViewModel;
using System.IO;

namespace WebShop.Controllers
{
 
    public class ItemController : Controller
    {
        private ECartDBEntities objECart;
        public ItemController()
        {
            objECart = new ECartDBEntities();
        }
        // GET: Item
        public ActionResult Index()
        {
            ItemViewModel objitemview = new ItemViewModel();
            objitemview.CategorySelectListItem = (from objCate in objECart.Categories
                                                  select new SelectListItem()
                                                  {
                                                      Text = objCate.CategoryName,
                                                      Value = objCate.CategoryId.ToString(),
                                                      Selected = true
                                                  });

            return View(objitemview);
        }
        [HttpPost]
        public JsonResult Index(ItemViewModel objitemview)
        {
            string NewImage = Guid.NewGuid() + Path.GetExtension(objitemview.Image.FileName);
            objitemview.Image.SaveAs(filename: Server.MapPath("~/Images/" + NewImage));

            Item objItem = new Item();
            objItem.Image = "~/Images/" + NewImage;
            objItem.CategoryId = objitemview.CategotyId;
            objItem.Description = objitemview.Description;
            objItem.ItemCode = objitemview.ItemCode;
            objItem.ItemId = Guid.NewGuid();
            objItem.Name = objitemview.Name;
            objItem.Price = objitemview.Price;
            objECart.Items.Add(objItem);
            objECart.SaveChangesAsync();

            return Json(data: new { Success = true, Message = " Add Successfully" }, JsonRequestBehavior.AllowGet);
        }
    }
}

WebShop/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;
using WebShop.ViewModel;
using System.IO;
using System.Threading.Tasks;


namespace WebShop.Controllers
{
    public class ShopController : Controller
    {
        private ECartDBEntities objECart;
        private List<ShoppingCartModel> ListShopcart;
        public ShopController()
        {
            objECart = new ECartDBEntities();
            ListShopcart = new List<ShoppingCartModel>();
        }
        // GET: Shop
        public ActionResult Index()
        {
            IEnumerable<ShoppingViewModel> listofshoppingViewModels = (from objItem in objECart.Items
                                                                       join objCate in objECart.Categories
                                                                       on objItem.CategoryId equals objCate.CategoryId
                                                                       select new ShoppingViewModel()
                                                                       {
                                                                           Image = objItem.Image,
                                                                           Name = objItem.Name,
                                                                           Description = objItem.Description,
                                                                           Price = objItem.Price,
                                                                           ItemId = objItem.ItemId,
                                                                           Category = objCate.CategoryName,
                                                                           ItemCode = objItem.ItemCode

                                                                       }).ToList();

            return View(listofshoppingViewModels);

        }
        [HttpPost]
        public JsonResult Index(string ItemId)
        {
            ShoppingCartModel objShopCart = new ShoppingCartModel();
            Item objItem = objECart.Items.Single(model => model.ItemId.ToString() == ItemId);
            if (Session["CartCounter"] != null)
            {
                ListShopcart = Session["cartitem"] as List<ShoppingCartModel>;
            }
            if (ListShopcart.Any(Model => Model.ItemId == ItemId))
            {
                objShopCart = ListShopcart.Single(model => model.ItemId == ItemId);
                objShopCart.Quantity = objShopCart.Quantity + 1;
                objShopCart.Total = objShopCart.Quantity * objShopCart.UnitPrice;
            }
            else
            {
                objShopCart.ItemId = ItemId;
                objShopCart.Image = objItem.Image;
                objShopCart.ItemName = objItem.Name;
                objShopCart.Quantity = 1;
                objShopCart.Total = objItem.Price;
                objShopCart.UnitPrice = objItem.Price;
                ListShopcart.Add(objShopCart);

            }
            Session["CartCounter"] = ListShopcart.Count;
            Session["cartitem"] = ListShopcart;

            return Json(data: new { Success = true, Counter = ListShopcart.Count }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Order()
        {
                ListShopcart = Session["cartitem"] as List<ShoppingCartModel>; 
            
            return View(ListShopcart);
        }
        public ActionResult Delete(string id)
        {
            List<ShoppingCartModel> cart = (List<ShoppingCartModel>)Session["cartitem"];
            var del = cart.Find(m => m.ItemId == id);           
            cart.Remove(del);
            Session["CartCounter"] = cart.Count;
            Session["cartitem"] = cart;

            return View("Order",cart);
        }

    }
}

WebShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Webshop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Add", "Index", "Item")
                    </li>
                    <li>
                        @Html.ActionLink("Store", "Index", "Shop")
                    </li>
                </ul>
                @Html.Partial("_order")
            </div>          
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

WebShop/Views/Shared/_order.cshtml
<ul class="nav navbar-nav navbar-right">
    <li>
        @if (Session["CartCounter"] == null)
        {
            @Html.ActionLink("Cart", "Order", "Shop", htmlAttributes: new { id = "cartitem" })
        }
        else
        {
            @Html.ActionLink("Cart(" + Session["CartCounter"] + ")","Order", "Shop", htmlAttributes: new { id = "cartitem" })
        }
        </li>
</ul>